name: GenTier
version: "1.0"
main: me.duncte123.gentier.GenTier
author: duncte123
commands:
    gentier:
      usage: "Only players can use this command" # Hack so we can just return false
      aliases:
        - cobblegentier
        - cobblecheck
        - generatortier
